# ------------------------------------------------------------------------------------------------ #
[versions]
## --- Plugins and more general stuff --- ##
#noinspection UnusedVersionCatalogEntry
jacoco = "0.8.14"
detekt = "1.23.8"

## --- Build Config and SDK --- ##
#noinspection UnusedVersionCatalogEntry
build-sdk-min = "20"
#noinspection UnusedVersionCatalogEntry
build-sdk-compile = "36"
#noinspection UnusedVersionCatalogEntry
build-tools = "36.1.0"

## JetBrains
jetbrains-kotlin = "2.3.0"
jetbrains-atomic = "0.31.0"
jetbrains-dokka = "2.1.0"
jetbrains-kover = "0.9.4"

## AndroidX
androidx-plugin = "9.0.0"

## Tools
ktlint = "14.0.1"
vanniktech-publish = "0.36.0"

# ------------------------------------------------------------------------------------------------ #
[libraries]
## JetBrains
jetbrains-dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "jetbrains-dokka" }
jetbrains-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "jetbrains-kotlin" }
jetbrains-multiplatform = { module = "org.jetbrains.kotlin.multiplatform:org.jetbrains.kotlin.multiplatform.gradle.plugin", version.ref = "jetbrains-kotlin" }
jetbrains-kover = { module = "org.jetbrains.kotlinx:kover-gradle-plugin", version.ref = "jetbrains-kover" }
jetbrains-kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "jetbrains-kotlin" }

## Androidx
androidx-library = { module = "com.android.kotlin.multiplatform.library:com.android.kotlin.multiplatform.library.gradle.plugin", version.ref = "androidx-plugin" }

## Tools
detekt = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
ktlint = { module = "org.jlleitschuh.gradle.ktlint:org.jlleitschuh.gradle.ktlint.gradle.plugin", version.ref = "ktlint" }
vanniktech-publish = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "vanniktech-publish" }

# ------------------------------------------------------------------------------------------------ #
[plugins]
jetbrains-atomic = { id = "org.jetbrains.kotlinx.atomicfu", version.ref = "jetbrains-atomic" }

# ------------------------------------------------------------------------------------------------ #
[bundles]
## Nothing Here Yet!
